app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgresdb
    username: postgresuser
    password: group6password
    pool-size: 30
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 10