CREATE TABLE users (
    userId UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE entry (
    entryId UUID NOT NULL PRIMARY KEY,
    userId UUID NOT NULL,
    title VARCHAR(100) NOT NULL,
    markdown VARCHAR NOT NULL,
    html VARCHAR NOT NULL
);