# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.8
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: Find and Replace DB URL
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "jdbc:postgresql://localhost:5432/postgresdb"
          replace: ${{ secrets.DB_URL }}
          include: "src/main/resources/application.yaml"

      - name: Find and Replace DB username
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "postgresuser"
          replace: ${{ secrets.DB_USERNAME }}
          include: "src/main/resources/application.yaml"

      - name: Find and Replace DB password
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "group6password"
          replace: ${{ secrets.DB_PASSWORD }}
          include: "src/main/resources/application.yaml"

      - name: Build with Maven
        run: mvn -B package --file API/pom.xml

      - name: Push to ECR
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: project590
          tags: v3, latest
          registry: 424106814116.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

